Update depth_layer no match for ‘operator=’ error
I recently checked out this branch and attempted to run catkin_make. There was an issue with how the cv::Ptr was being set. 

This is fixed by setting the normals_estimator_ pointer similarly to how the plane_estimator_ pointer is being set. The package can now compile. I am confused why I needed to change this, but I am curious to learn why.

The error below would occur:
[ 97%] Building CXX object navigation/move_base/CMakeFiles/move_base.dir/src/move_base.cpp.o
/home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp: In member function ‘void costmap_2d::FetchDepthLayer::depthImageCallback(const ConstPtr&)’:
/home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:239:28: error: no match for ‘operator=’ (operand types are ‘cv::Ptr<cv::rgbd::RgbdNormals>’ and ‘cv::rgbd::RgbdNormals*’)
       normals_estimator_ = new RgbdNormals(cv_ptr->image.rows,cv_ptr->image.cols,  cv_ptr->image.depth(),K_);
                            ^~~~
In file included from /usr/local/include/opencv2/core/cvstd.hpp:1033:0,
                 from /usr/local/include/opencv2/core/base.hpp:58,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /opt/ros/melodic/include/cv_bridge/cv_bridge.h:43,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/include/fetch_depth_layer/depth_layer.h:37,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:32:
/usr/local/include/opencv2/core/ptr.inl.hpp:160:9: note: candidate: cv::Ptr<T>& cv::Ptr<T>::operator=(const cv::Ptr<T>&) [with T = cv::rgbd::RgbdNormals]
 Ptr<T>& Ptr<T>::operator = (const Ptr<T>& o)
         ^~~~~~
/usr/local/include/opencv2/core/ptr.inl.hpp:160:9: note:   no known conversion for argument 1 from ‘cv::rgbd::RgbdNormals*’ to ‘const cv::Ptr<cv::rgbd::RgbdNormals>&’
In file included from /usr/local/include/opencv2/core/base.hpp:58:0,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /opt/ros/melodic/include/cv_bridge/cv_bridge.h:43,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/include/fetch_depth_layer/depth_layer.h:37,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:32:
/usr/local/include/opencv2/core/cvstd.hpp:333:10: note: candidate: template<class Y> cv::Ptr<T>& cv::Ptr<T>::operator=(const cv::Ptr<Y>&) [with Y = Y; T = cv::rgbd::RgbdNormals]
     Ptr& operator = (const Ptr<Y>& o);
          ^~~~~~~~
/usr/local/include/opencv2/core/cvstd.hpp:333:10: note:   template argument deduction/substitution failed:
/home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:239:28: note:   mismatched types ‘const cv::Ptr<T>’ and ‘cv::rgbd::RgbdNormals*’
       normals_estimator_ = temp;
                            ^~~~
In file included from /usr/local/include/opencv2/core/cvstd.hpp:1033:0,
                 from /usr/local/include/opencv2/core/base.hpp:58,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /opt/ros/melodic/include/cv_bridge/cv_bridge.h:43,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/include/fetch_depth_layer/depth_layer.h:37,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:32:
/usr/local/include/opencv2/core/ptr.inl.hpp:263:9: note: candidate: cv::Ptr<T>& cv::Ptr<T>::operator=(cv::Ptr<T>&&) [with T = cv::rgbd::RgbdNormals]
 Ptr<T>& Ptr<T>::operator = (Ptr<T>&& o)
         ^~~~~~
/usr/local/include/opencv2/core/ptr.inl.hpp:263:9: note:   no known conversion for argument 1 from ‘cv::rgbd::RgbdNormals*’ to ‘cv::Ptr<cv::rgbd::RgbdNormals>&&’
fetch_ros/fetch_depth_layer/CMakeFiles/fetch_depth_layer.dir/build.make:62: recipe for target 'fetch_ros/fetch_depth_layer/CMakeFiles/fetch_depth_layer.dir/src/depth_layer.cpp.o' failed
make[2]: *** [fetch_ros/fetch_depth_layer/CMakeFiles/fetch_depth_layer.dir/src/depth_layer.cpp.o] Error 1
CMakeFiles/Makefile2:10133: recipe for target 'fetch_ros/fetch_depth_layer/CMakeFiles/fetch_depth_layer.dir/all' failed
make[1]: *** [fetch_ros/fetch_depth_layer/CMakeFiles/fetch_depth_layer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX shared library /home/josiah/PycharmProjects/fetch_robot_ws/devel/lib/libmove_base.so
[ 98%] Built target move_base
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed