[fetch_depth_layer][OpenCV-4] operator= compile error
This fixes no match for ‘operator=’ error with OpenCV4 and how the cv::Ptr was being set.

Fixed by setting the normals_estimator_ pointer similarly to how the plane_estimator_ pointer is being set.

The error below would occur:

    fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:239:28:
    error: no match for ‘operator=’ (operand types are ‘cv::Ptr<cv::rgbd::RgbdNormals>’ and ‘cv::rgbd::RgbdNormals*’)
           normals_estimator_ = new RgbdNormals(cv_ptr->image.rows,cv_ptr->image.cols,  cv_ptr->image.depth(),K_);
                                ^~~~

This closes #82